import { notFound } from 'next/navigation';
import { CafeMenuClient } from './ui';

type MenuItem = {
	id: string;
	name: string;
	/** Короткий символ для компактной строки в мобильном меню */
	emoji: string;
	description?: string;
	ingredients: string[];
	tags: Array<'spicy' | 'vegan' | 'hit'>;
	priceRub: number;
	image: { kind: 'gradient'; a: string; b: string };
	isAvailable?: boolean;
};

type MenuCategory = {
	id: string;
	name: string;
	/** Эмодзи для чипа категории */
	icon: string;
	items: MenuItem[];
};

type Cafe = {
	id: string;
	name: string;
	slug: string;
	subtitle?: string;
	categories: MenuCategory[];
};

/** Демо-меню для презентации бизнесу: много категорий и позиций */
const demoCafe: Cafe = {
	id: 'demo',
	name: 'Кафе «Лавка»',
	slug: 'demo',
	subtitle: 'Домашняя кухня • Завтраки с 8:00 • Вечером — вино',
	categories: [
		{
			id: 'cat-breakfast',
			name: 'Завтраки',
			icon: '🥐',
			items: [
				{
					id: 'bf-avocado',
					name: 'Авокадо-тост с яйцом пашот',
					emoji: '🥑',
					description: 'Хлеб на закваске, пашот, авокадо, микрозелень.',
					ingredients: ['авокадо', 'яйцо', 'хлеб', 'лимон'],
					tags: ['hit'],
					priceRub: 320,
					image: { kind: 'gradient', a: '#84cc16', b: '#22c55e' },
				},
				{
					id: 'bf-syrniki',
					name: 'Сырники со сметаной и ягодами',
					emoji: '🫐',
					description: 'Творог 9%, ягодный соус собственного приготовления.',
					ingredients: ['творог', 'яйцо', 'мука', 'сметана', 'ягоды'],
					tags: ['hit'],
					priceRub: 280,
					image: { kind: 'gradient', a: '#a78bfa', b: '#ec4899' },
				},
				{
					id: 'bf-oatmeal',
					name: 'Овсяная каша на кокосовом молоке',
					emoji: '🥣',
					description: 'С бананом, мёдом и семенами льна.',
					ingredients: ['овсянка', 'кокосовое молоко', 'банан', 'мёд'],
					tags: ['vegan'],
					priceRub: 220,
					image: { kind: 'gradient', a: '#f59e0b', b: '#eab308' },
				},
				{
					id: 'bf-omelet',
					name: 'Омлет с ветчиной и сыром',
					emoji: '🍳',
					description: 'Три яйца, ветчина, моцарелла, зелень.',
					ingredients: ['яйцо', 'ветчина', 'сыр'],
					tags: [],
					priceRub: 260,
					image: { kind: 'gradient', a: '#fcd34d', b: '#f97316' },
				},
				{
					id: 'bf-blini',
					name: 'Блины с лососем и сливочным сыром',
					emoji: '🥞',
					description: 'Тонкие блины, слабосолёный лосось, укроп.',
					ingredients: ['блины', 'лосось', 'сыр', 'укроп'],
					tags: ['hit'],
					priceRub: 420,
					image: { kind: 'gradient', a: '#38bdf8', b: '#6366f1' },
				},
				{
					id: 'bf-english',
					name: 'Английский завтрак',
					emoji: '🍳',
					description: 'Яичница, бекон, фасоль, грибы, тост, сок.',
					ingredients: ['яйцо', 'бекон', 'фасоль', 'грибы', 'хлеб'],
					tags: [],
					priceRub: 450,
					image: { kind: 'gradient', a: '#ef4444', b: '#b45309' },
				},
			],
		},
		{
			id: 'cat-salads',
			name: 'Салаты',
			icon: '🥗',
			items: [
				{
					id: 'salad-caesar',
					name: 'Цезарь с курицей',
					emoji: '🥗',
					description: 'Романо, пармезан, гренки, соус цезарь.',
					ingredients: ['курица', 'салат', 'пармезан', 'гренки'],
					tags: ['hit'],
					priceRub: 420,
					image: { kind: 'gradient', a: '#4ade80', b: '#16a34a' },
				},
				{
					id: 'salad-greek',
					name: 'Греческий салат',
					emoji: '🫒',
					description: 'Овощи, фета, оливки, оливковое масло.',
					ingredients: ['огурец', 'томат', 'фета', 'оливки'],
					tags: ['vegan'],
					priceRub: 380,
					image: { kind: 'gradient', a: '#22d3ee', b: '#0ea5e9' },
				},
				{
					id: 'salad-beef',
					name: 'Салат с ростбифом и рукколой',
					emoji: '🥩',
					description: 'Ростбиф medium, руккола, вяленые томаты, бальзамик.',
					ingredients: ['говядина', 'руккола', 'томат', 'бальзамик'],
					tags: [],
					priceRub: 520,
					image: { kind: 'gradient', a: '#dc2626', b: '#7f1d1d' },
				},
				{
					id: 'salad-vitamin',
					name: 'Витаминный с фетой и гранатом',
					emoji: '🥬',
					description: 'Микс салатов, гранат, орехи, медово-горчичная заправка.',
					ingredients: ['салат', 'фета', 'гранат', 'орехи'],
					tags: ['vegan'],
					priceRub: 360,
					image: { kind: 'gradient', a: '#10b981', b: '#059669' },
				},
				{
					id: 'salad-shrimp',
					name: 'Тёплый салат с креветками',
					emoji: '🦐',
					description: 'Тигровые креветки, спаржа, перец гриль, соус понзу.',
					ingredients: ['креветки', 'спаржа', 'перец', 'соя'],
					tags: ['hit'],
					priceRub: 540,
					image: { kind: 'gradient', a: '#f472b6', b: '#db2777' },
				},
			],
		},
		{
			id: 'cat-soups',
			name: 'Супы',
			icon: '🍲',
			items: [
				{
					id: 'soup-borscht',
					name: 'Борщ с говядиной',
					emoji: '🍲',
					description: 'Наваристый, со сметаной и чесночным пампушком.',
					ingredients: ['говядина', 'свёкла', 'капуста', 'сметана'],
					tags: ['hit'],
					priceRub: 320,
					image: { kind: 'gradient', a: '#b91c1c', b: '#7f1d1d' },
				},
				{
					id: 'soup-mushroom',
					name: 'Крем-суп из шампиньонов',
					emoji: '🍄',
					description: 'С трюфельным маслом и гренками.',
					ingredients: ['шампиньоны', 'сливки', 'лук', 'трюфель'],
					tags: ['vegan'],
					priceRub: 290,
					image: { kind: 'gradient', a: '#78716c', b: '#44403c' },
				},
				{
					id: 'soup-solyanka',
					name: 'Солянка мясная',
					emoji: '🥘',
					description: 'Ассорти мясное, соленья, лимон, сметана.',
					ingredients: ['колбаса', 'говядина', 'огурец', 'томат'],
					tags: [],
					priceRub: 340,
					image: { kind: 'gradient', a: '#ea580c', b: '#c2410c' },
				},
				{
					id: 'soup-pumpkin',
					name: 'Тыквенный крем-суп',
					emoji: '🎃',
					description: 'С семечками тыквы и кокосовыми сливками.',
					ingredients: ['тыква', 'кокос', 'лук', 'имбирь'],
					tags: ['vegan'],
					priceRub: 270,
					image: { kind: 'gradient', a: '#f97316', b: '#ea580c' },
				},
				{
					id: 'soup-fish',
					name: 'Уха из форели',
					emoji: '🐟',
					description: 'С овощами и зеленью, подаётся с лимоном.',
					ingredients: ['форель', 'картофель', 'морковь', 'лук'],
					tags: [],
					priceRub: 390,
					image: { kind: 'gradient', a: '#0ea5e9', b: '#0369a1' },
				},
			],
		},
		{
			id: 'cat-mains',
			name: 'Горячее',
			icon: '🍽️',
			items: [
				{
					id: 'main-kiev',
					name: 'Котлета по-киевски с пюре',
					emoji: '🍗',
					description: 'Куриное филе, масло с зеленью, картофельное пюре.',
					ingredients: ['курица', 'масло', 'картофель'],
					tags: ['hit'],
					priceRub: 480,
					image: { kind: 'gradient', a: '#fbbf24', b: '#d97706' },
				},
				{
					id: 'main-steak',
					name: 'Стейк стриплойн',
					emoji: '🥩',
					description: 'Прожарка на выбор, соус перечный или борделез.',
					ingredients: ['говядина', 'масло', 'чеснок'],
					tags: ['hit'],
					priceRub: 890,
					image: { kind: 'gradient', a: '#991b1b', b: '#451a03' },
				},
				{
					id: 'main-salmon',
					name: 'Филе лосося с овощами гриль',
					emoji: '🐟',
					description: 'Лосось атлантический, цукини, перец, соус лимонный.',
					ingredients: ['лосось', 'цукини', 'перец', 'лимон'],
					tags: [],
					priceRub: 720,
					image: { kind: 'gradient', a: '#fb923c', b: '#ea580c' },
				},
				{
					id: 'main-ribs',
					name: 'Рёбрышки BBQ с дольками',
					emoji: '🍖',
					description: 'Свинина низкая варка, соус барбекю, запечённый картофель.',
					ingredients: ['свинина', 'соус', 'картофель'],
					tags: ['spicy'],
					priceRub: 560,
					image: { kind: 'gradient', a: '#b45309', b: '#78350f' },
				},
				{
					id: 'main-chicken',
					name: 'Куриная грудка су-вид',
					emoji: '🍗',
					description: 'С овощами и соусом песто.',
					ingredients: ['курица', 'базилик', 'кабачок', 'перец'],
					tags: [],
					priceRub: 520,
					image: { kind: 'gradient', a: '#86efac', b: '#22c55e' },
				},
			],
		},
		{
			id: 'cat-pasta',
			name: 'Паста',
			icon: '🍝',
			items: [
				{
					id: 'pasta-carbonara',
					name: 'Паста карбонара',
					emoji: '🍝',
					description: 'Спагетти, гуанчиале, яйцо, пекорино.',
					ingredients: ['паста', 'бекон', 'яйцо', 'сыр'],
					tags: ['hit'],
					priceRub: 420,
					image: { kind: 'gradient', a: '#fde68a', b: '#f59e0b' },
				},
				{
					id: 'pasta-bolognese',
					name: 'Тальятелле болоньезе',
					emoji: '🍅',
					description: 'Мясной рагу томлёный 4 часа, пармезан.',
					ingredients: ['паста', 'говядина', 'томат', 'лук'],
					tags: [],
					priceRub: 450,
					image: { kind: 'gradient', a: '#ef4444', b: '#b91c1c' },
				},
				{
					id: 'pasta-shrimp',
					name: 'Паста с креветками',
					emoji: '🦐',
					description: 'Томатный соус, чеснок, базилик, креветки.',
					ingredients: ['паста', 'креветки', 'томат', 'чеснок'],
					tags: [],
					priceRub: 510,
					image: { kind: 'gradient', a: '#f9a8d4', b: '#be185d' },
				},
				{
					id: 'pasta-risotto',
					name: 'Ризотто с белыми грибами',
					emoji: '🍚',
					description: 'Арборио, белое вино, пармезан, петрушка.',
					ingredients: ['рис', 'грибы', 'вино', 'сыр'],
					tags: ['vegan'],
					priceRub: 480,
					image: { kind: 'gradient', a: '#d6d3d1', b: '#78716c' },
				},
				{
					id: 'pasta-lasagna',
					name: 'Лазанья мясная',
					emoji: '🧀',
					description: 'Домашняя паста, соус бешамель, моцарелла.',
					ingredients: ['лазанья', 'говядина', 'томат', 'сыр'],
					tags: [],
					priceRub: 440,
					image: { kind: 'gradient', a: '#fcd34d', b: '#d97706' },
				},
			],
		},
		{
			id: 'cat-burgers',
			name: 'Бургеры',
			icon: '🍔',
			items: [
				{
					id: 'burger-classic',
					name: 'Классический бургер',
					emoji: '🍔',
					description: 'Булка бриошь, котлета из мраморной говядины, чеддер.',
					ingredients: ['говядина', 'сыр', 'салат', 'томат', 'соус'],
					tags: ['hit'],
					priceRub: 390,
					image: { kind: 'gradient', a: '#34d399', b: '#22c55e' },
				},
				{
					id: 'burger-chicken',
					name: 'Чикен бургер',
					emoji: '🐔',
					description: 'Куриная котлета в панировке, коул-слоу, соус ранч.',
					ingredients: ['курица', 'капуста', 'соус'],
					tags: [],
					priceRub: 360,
					image: { kind: 'gradient', a: '#fbbf24', b: '#fb7185' },
				},
				{
					id: 'burger-spicy',
					name: 'Острый бургер чили',
					emoji: '🌶️',
					description: 'Джалапеньо, острый соус, бекон, лук красный.',
					ingredients: ['говядина', 'перец', 'бекон', 'лук'],
					tags: ['spicy', 'hit'],
					priceRub: 410,
					image: { kind: 'gradient', a: '#f87171', b: '#dc2626' },
				},
				{
					id: 'burger-vegan',
					name: 'Веган-бургер',
					emoji: '🌱',
					description: 'Котлета из нута и грибов, томаты, веган-майонез.',
					ingredients: ['нут', 'грибы', 'томат', 'салат'],
					tags: ['vegan'],
					priceRub: 340,
					image: { kind: 'gradient', a: '#4ade80', b: '#15803d' },
				},
			],
		},
		{
			id: 'cat-pizza',
			name: 'Пицца',
			icon: '🍕',
			items: [
				{
					id: 'pizza-margherita',
					name: 'Пицца Маргарита',
					emoji: '🍕',
					description: 'Тесто 48 ч, томаты Сан-Марцано, моцарелла, базилик. 30 см.',
					ingredients: ['тесто', 'томат', 'моцарелла', 'базилик'],
					tags: ['hit'],
					priceRub: 520,
					image: { kind: 'gradient', a: '#fca5a5', b: '#eab308' },
				},
				{
					id: 'pizza-pepperoni',
					name: 'Пицца Пепперони',
					emoji: '🍕',
					description: 'Пепперони, моцарелла, томатный соус. 30 см.',
					ingredients: ['тесто', 'колбаса', 'сыр', 'томат'],
					tags: ['hit'],
					priceRub: 590,
					image: { kind: 'gradient', a: '#ef4444', b: '#991b1b' },
				},
				{
					id: 'pizza-4cheese',
					name: 'Четыре сыра',
					emoji: '🧀',
					description: 'Моцарелла, горгонзола, пармезан, чеддер. 30 см.',
					ingredients: ['тесто', 'сыр', 'сливки'],
					tags: [],
					priceRub: 640,
					image: { kind: 'gradient', a: '#fde047', b: '#ca8a04' },
				},
				{
					id: 'pizza-mushroom',
					name: 'Грибная с трюфелем',
					emoji: '🍄',
					description: 'Шампиньоны, трюфельное масло, руккола. 30 см.',
					ingredients: ['тесто', 'грибы', 'трюфель', 'сыр'],
					tags: [],
					priceRub: 680,
					image: { kind: 'gradient', a: '#a8a29e', b: '#57534e' },
				},
				{
					id: 'pizza-meat',
					name: 'Мясная',
					emoji: '🥓',
					description: 'Ветчина, бекон, пепперони, говядина. 30 см.',
					ingredients: ['тесто', 'ветчина', 'бекон', 'говядина'],
					tags: [],
					priceRub: 670,
					image: { kind: 'gradient', a: '#b45309', b: '#7c2d12' },
				},
			],
		},
		{
			id: 'cat-starters',
			name: 'Закуски',
			icon: '🍟',
			items: [
				{
					id: 'fries',
					name: 'Картофель фри',
					emoji: '🍟',
					description: 'Хрустящий, 150 г, соус на выбор.',
					ingredients: ['картофель', 'соль'],
					tags: ['vegan'],
					priceRub: 160,
					image: { kind: 'gradient', a: '#60a5fa', b: '#a78bfa' },
				},
				{
					id: 'potato-wedges',
					name: 'Картофель по-деревенски',
					emoji: '🥔',
					description: 'С чесночным соусом и паприкой.',
					ingredients: ['картофель', 'чеснок', 'паприка'],
					tags: ['vegan'],
					priceRub: 190,
					image: { kind: 'gradient', a: '#d97706', b: '#92400e' },
				},
				{
					id: 'wings',
					name: 'Куриные крылья BBQ',
					emoji: '🍗',
					description: '6 шт, соус барбекю или острый.',
					ingredients: ['курица', 'соус'],
					tags: ['spicy'],
					priceRub: 350,
					image: { kind: 'gradient', a: '#ea580c', b: '#9a3412' },
				},
				{
					id: 'nuggets',
					name: 'Наггетсы',
					emoji: '🍗',
					description: '6 шт + соус на выбор.',
					ingredients: ['курица', 'панировка', 'соус'],
					tags: [],
					priceRub: 210,
					image: { kind: 'gradient', a: '#fb7185', b: '#f59e0b' },
				},
				{
					id: 'onion-rings',
					name: 'Луковые кольца',
					emoji: '🧅',
					description: 'В панировке, с соусом барбекю.',
					ingredients: ['лук', 'панировка'],
					tags: ['vegan'],
					priceRub: 220,
					image: { kind: 'gradient', a: '#fde68a', b: '#d97706' },
				},
				{
					id: 'mozzarella',
					name: 'Сырные палочки моцарелла',
					emoji: '🧀',
					description: '5 шт, малиновый соус.',
					ingredients: ['моцарелла', 'панировка'],
					tags: [],
					priceRub: 280,
					image: { kind: 'gradient', a: '#fef08a', b: '#eab308' },
				},
			],
		},
		{
			id: 'cat-desserts',
			name: 'Десерты',
			icon: '🍰',
			items: [
				{
					id: 'dessert-tiramisu',
					name: 'Тирамису',
					emoji: '🍰',
					description: 'Маскарпоне, эспрессо, какао.',
					ingredients: ['маскарпоне', 'кофе', 'яйцо', 'печенье'],
					tags: ['hit'],
					priceRub: 290,
					image: { kind: 'gradient', a: '#78350f', b: '#451a03' },
				},
				{
					id: 'dessert-cheesecake',
					name: 'Чизкейк «Нью-Йорк»',
					emoji: '🍰',
					description: 'Классический, с ягодным кули.',
					ingredients: ['сыр', 'сахар', 'яйцо', 'ягоды'],
					tags: [],
					priceRub: 310,
					image: { kind: 'gradient', a: '#fce7f3', b: '#db2777' },
				},
				{
					id: 'dessert-brownie',
					name: 'Брауни с мороженым',
					emoji: '🍫',
					description: 'Тёплый шоколадный пирог, ванильное мороженое.',
					ingredients: ['шоколад', 'масло', 'мука', 'мороженое'],
					tags: [],
					priceRub: 260,
					image: { kind: 'gradient', a: '#713f12', b: '#431407' },
				},
				{
					id: 'dessert-icecream',
					name: 'Мороженое (2 шарика)',
					emoji: '🍨',
					description: 'Ваниль, шоколад, фисташка, карамель — на выбор.',
					ingredients: ['молоко', 'сахар', 'сливки'],
					tags: [],
					priceRub: 180,
					image: { kind: 'gradient', a: '#bae6fd', b: '#a855f7' },
				},
				{
					id: 'dessert-panna',
					name: 'Панна-котта с манго',
					emoji: '🥭',
					description: 'Нежный десерт на сливках, манговое пюре.',
					ingredients: ['сливки', 'желатин', 'манго', 'ваниль'],
					tags: [],
					priceRub: 240,
					image: { kind: 'gradient', a: '#fcd34d', b: '#f97316' },
				},
			],
		},
		{
			id: 'cat-drinks',
			name: 'Напитки',
			icon: '🥤',
			items: [
				{
					id: 'lemonade',
					name: 'Лимонад домашний',
					emoji: '🍋',
					description: '0,4 л: классический, малина-мята, имбирь-лайм.',
					ingredients: ['лимон', 'сахар', 'вода', 'мята'],
					tags: ['hit', 'vegan'],
					priceRub: 180,
					image: { kind: 'gradient', a: '#22c55e', b: '#38bdf8' },
				},
				{
					id: 'mors',
					name: 'Морс ягодный',
					emoji: '🫐',
					description: '0,4 л, собственного отжима.',
					ingredients: ['ягоды', 'сахар', 'вода'],
					tags: ['vegan'],
					priceRub: 140,
					image: { kind: 'gradient', a: '#7c3aed', b: '#ec4899' },
				},
				{
					id: 'juice',
					name: 'Сок в ассортименте',
					emoji: '🧃',
					description: 'Апельсин, яблоко, виноград — 0,3 л.',
					ingredients: ['сок'],
					tags: ['vegan'],
					priceRub: 120,
					image: { kind: 'gradient', a: '#fb923c', b: '#ea580c' },
				},
				{
					id: 'cola',
					name: 'Кола / спрайт',
					emoji: '🥤',
					description: '0,5 л, стеклянная бутылка.',
					ingredients: ['газировка'],
					tags: ['vegan'],
					priceRub: 170,
					image: { kind: 'gradient', a: '#0ea5e9', b: '#6366f1' },
				},
				{
					id: 'water',
					name: 'Минеральная вода',
					emoji: '💧',
					description: '0,5 л, с газом / без.',
					ingredients: ['вода'],
					tags: ['vegan'],
					priceRub: 90,
					image: { kind: 'gradient', a: '#7dd3fc', b: '#0284c7' },
				},
			],
		},
		{
			id: 'cat-coffee',
			name: 'Кофе и чай',
			icon: '☕',
			items: [
				{
					id: 'coffee-espresso',
					name: 'Эспрессо',
					emoji: '☕',
					description: 'Смесь арабика / робуста, обжарка под эспрессо.',
					ingredients: ['кофе', 'вода'],
					tags: ['vegan'],
					priceRub: 120,
					image: { kind: 'gradient', a: '#44403c', b: '#292524' },
				},
				{
					id: 'coffee-americano',
					name: 'Американо',
					emoji: '☕',
					description: 'Двойной эспрессо + горячая вода.',
					ingredients: ['кофе', 'вода'],
					tags: ['vegan'],
					priceRub: 130,
					image: { kind: 'gradient', a: '#57534e', b: '#1c1917' },
				},
				{
					id: 'coffee-cappuccino',
					name: 'Капучино',
					emoji: '☕',
					description: 'Эспрессо, молоко 3,2%, молочная пена.',
					ingredients: ['кофе', 'молоко'],
					tags: [],
					priceRub: 180,
					image: { kind: 'gradient', a: '#d6d3d1', b: '#78716c' },
				},
				{
					id: 'coffee-latte',
					name: 'Латте',
					emoji: '☕',
					description: 'Эспрессо, больше молока, можно с сиропом.',
					ingredients: ['кофе', 'молоко'],
					tags: [],
					priceRub: 190,
					image: { kind: 'gradient', a: '#e7e5e4', b: '#a8a29e' },
				},
				{
					id: 'coffee-raf',
					name: 'Раф кофе',
					emoji: '☕',
					description: 'Эспрессо, сливки, ванильный сахар.',
					ingredients: ['кофе', 'сливки', 'ваниль'],
					tags: ['hit'],
					priceRub: 200,
					image: { kind: 'gradient', a: '#fef3c7', b: '#d97706' },
				},
				{
					id: 'cocoa',
					name: 'Какао',
					emoji: '🍫',
					description: 'Молоко, бельгийский какао, зефирка.',
					ingredients: ['молоко', 'какао', 'сахар'],
					tags: [],
					priceRub: 160,
					image: { kind: 'gradient', a: '#78350f', b: '#431407' },
				},
				{
					id: 'tea-pot',
					name: 'Чай в ассортименте',
					emoji: '🫖',
					description: 'Чайник 600 мл: чёрный, зелёный, травяной.',
					ingredients: ['чай', 'вода'],
					tags: ['vegan'],
					priceRub: 250,
					image: { kind: 'gradient', a: '#86efac', b: '#166534' },
				},
			],
		},
	],
};

function getCafeBySlug(slug: string): Cafe | null {
	if (slug === 'demo') return demoCafe;
	return null;
}

export default async function CafePage({
	params,
	searchParams,
}: {
	params: Promise<{ slug: string }>;
	searchParams: Promise<{ t?: string }>;
}) {
	const { slug } = await params;
	const { t } = await searchParams;
	const cafe = getCafeBySlug(slug);
	if (!cafe) notFound();

	const tableLabel = t ? `Стол ${t}` : undefined;

	return <CafeMenuClient cafe={cafe} tableLabel={tableLabel} />;
}
